# AWS infra support resources for tsw demo project
AWSTemplateFormatVersion: "2010-09-09"
Description: tsw demo infra resources
Parameters:
    Stage:
        Type: String
        Default: dev

Resources:
    # Deployment bucket for all serverless modules
    TSWDemoDeployBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            BucketName: !Sub "${Stage}-tsw-demo-deployment"
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                          SSEAlgorithm: AES256
            LifecycleConfiguration:
                Rules:
                    - Status: Enabled
                      Id: "Delete incomplete multipart upload after 1 day"
                      AbortIncompleteMultipartUpload:
                          DaysAfterInitiation: 1
    # Lambda execution role for aws lambda
    TSWDemoLambdaRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub "${Stage}-tsw-demo-lambda-role"
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - codepipeline.amazonaws.com
                              - cloudformation.amazonaws.com
                              - lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - !Ref TSWDemoLambdaDynamoDBPolicy
                - !Ref TSWDemoLambdaS3Policy
                - !Ref TSWDemoInvokeLambdaPolicy
                - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

    TSWDemoLambdaDynamoDBPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            ManagedPolicyName: !Sub "${Stage}_TSWDemoLambdaDynamoDBPolicy"
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Action: dynamodb:*
                      Effect: Allow
                      Resource: "*"

    TSWDemoLambdaS3Policy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            ManagedPolicyName: !Sub "${Stage}_TSWDemoLambdaS3Policy"
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Action: s3:*
                      Effect: Allow
                      Resource: "*"

    TSWDemoInvokeLambdaPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            ManagedPolicyName: !Sub "${Stage}_TSWDemoInvokeLambdaPolicy"
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Action: lambda:*
                      Resource: "*"
