name:

on:
    push:
        branches:
            - "**" # matches every branch

jobs:
    pre-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up environment
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Prepare
              run: |
                  npm install
                  npm run pre-commit
                  npm test --coverage
            - name: Test
              run: |
                  npm test
